import time
from selenium import webdriver

driver = webdriver.Firefox(executable_path="C:\Selenium Drivers\geckodriver-v0.26.0-win64\geckodriver.exe")
driver.get("http://newtours.demoaut.com/")
user_name = "mercury"
password = "mercury"
uname = driver.find_element_by_name("userName")
pwd = driver.find_element_by_name("password")

print(uname.is_enabled())
print(pwd.is_displayed())
print(pwd.is_selected())

uname.send_keys(user_name)
pwd.send_keys(password)
driver.find_element_by_name("login").click()
time.sleep(10)
single_trip = driver.find_element_by_css_selector("input[type=radio][value=oneway]")
print(single_trip.is_selected())
if not single_trip.is_selected():
    driver.find_element_by_css_selector("input[type=radio][value=oneway]").click()
    driver.find_element_by_name("passCount").send_keys(1)
    driver.find_element_by_name("fromPort").send_keys("London")
    time.sleep(1)
    driver.find_element_by_name("fromMonth").send_keys("March")
    time.sleep(1)
    driver.find_element_by_name("fromDay").send_keys("18")
    time.sleep(1)
    driver.find_element_by_name("toPort").send_keys("Paris")
    time.sleep(1)
    driver.find_element_by_name("toMonth").send_keys("June")
    driver.find_element_by_name("toDay").send_keys("20")
    driver.find_element_by_css_selector("input[type=radio][value=First]").click()
    driver.find_element_by_name("airline").send_keys("Unified Airlines")
    driver.find_element_by_name("findFlights").click()
    time.sleep(4)
    driver.find_element_by_xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table[1]/tbody/tr[7]/td[1]/input").click()
    driver.find_element_by_xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table[2]/tbody/tr[9]/td[1]/input").click()
    driver.find_element_by_name("reserveFlights").click()
    driver.find_element_by_name("passFirst0").send_keys("kiran")
    time.sleep(1)
    driver.find_element_by_name("passLast0").send_keys("sai")
    time.sleep(1)
    driver.find_element_by_name("pass.0.meal").send_keys("Hindu")
    time.sleep(1)
    driver.find_element_by_name("creditCard").send_keys("Visa")
    time.sleep(1)
    driver.find_element_by_name("creditnumber").send_keys("1234123412341234")
    time.sleep(1)
    driver.find_element_by_name("cc_exp_dt_mn").send_keys("10")
    time.sleep(1)
    driver.find_element_by_name("cc_exp_dt_yr").send_keys("2010")
    time.sleep(1)
    driver.find_element_by_name("cc_frst_name").send_keys("sai")
    time.sleep(1)
    driver.find_element_by_name("cc_last_name").send_keys("kiran")
    time.sleep(1)
    driver.find_element_by_name("billAddress1").send_keys("1-10-2563-4651")
    time.sleep(1)
    driver.find_element_by_name("billCity").send_keys("Patna")
    time.sleep(1)
    driver.find_element_by_name("billState").send_keys("Delhi")
    time.sleep(1)
    driver.find_element_by_name("billZip").send_keys("12345")
    time.sleep(1)
    driver.find_element_by_name("billCity").send_keys("patna")
    time.sleep(1)
    driver.find_element_by_name("billCountry").send_keys("INDIA")
    time.sleep(1)
    driver.find_element_by_name("ticketLess").click()
    driver.find_element_by_name("buyFlights").click()

time.sleep(10)

driver.close()
